package main
// THIS FILE IS AUTOGENERATED
// DO NOT EDIT
func getVersionNo() string { return "1.0.000008" }
func getBuildMachine() string { return "Steves-MacBook-Pro-2.local" }
func getBuildTime() string { return "Tue Apr  4 16:04:24 PDT 2017" }
